POST http://20.244.56.144/evaluation-service/auth
Content-Type: application/json
{
"email": "2205732@kiit.ac.in",
  "name": "hurshikesh sahu",
  "rollNo": "two two zero five seven three two",
  "accessCode": "nwpwrZ",
  "clientID": "b350d311-c9e6-4e0d-a1af-8b9d8c8aa96d",
  "clientSecret": "KgnyEeXDPeQZYkrF"
}